server:
  port: 8089

#database source url
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Monika91%
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:
